### ISSUE TITLE
Where has Mostapha been?

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-tools.github.io#1]
Mostapha was here:

![image](https://cloud.githubusercontent.com/assets/547626/17766633/f05f8d18-64e0-11e6-8ffc-65c1d5cfb259.png)

@ladybug-analysis-tools/owners @mdahlhausen

There's a lot going on with mapping. Sadly, 3D mapping - projects like Google Earth - are old, slow and finicky.

Can we disrupt that?
## [Elevations View: Teheran](https://jaanga.github.io/terrain3/elevations-core3/elevations-core3-r1.html#file=../elevations-data/elevations-data-04//tehran-iran_9_328_200_3_3_510_510_.json)

~~## [Elevations View Path CSV](https://jaanga.github.io/terrain3/elevations/elevations-view-path-csv/)~~

## [Oakland Gran Fondo 2016 3D Viewer R12.2]( https://cynthiaarmour.github.io/oakland-gran-fondo-2016/r12/index.html )
* Looks like there's an issue here: you must reload after opening.

Can we make 3D geography easy enough so it's part of the normal investigation into locale climate conditions?

**2017-05-31 - Update**: update broken links

**Comment by mostaphaRoudsari** [comment]
@theo-armour this is very cool and @chriswmackey is the one to answer the question. Both links are broken though.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

Oops! Will fax later today.

**Comment by theo-armour** [comment]
@mostaphaRoudsari @chriswmackey 

Links fixed - mostly
