### ISSUE TITLE
Rename 'Owners' team to 'Core' team

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-tools.github.io#11]
GitHub points out that the 'Owner' team no longer has the power it used to have. In order to avoid any confusion, it's best to rename the team. They suggest the name 'Core'.

BTW, I joined myself to the team.

Unless I hear otherwise or somebody else gets there first, I will do the renaming in a day or two.

**Comment by mostaphaRoudsari** [comment]
I didn't know about it. Thanks. It's renamed to @ladybug-tools/core. I also renamed other teams to ensure all the team names are lowercase.
