### ISSUE TITLE
Updates to Eval Read Me

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-tools.github.io#12]
@ladybug-tools/owners 

I have added quite a bit of text to the Eval Read Me. It's all a work in progress. I plan to add quite a bit more about 'Early-design modeling'

### [New Web Site Read Me]( https://github.com/ladybug-tools/ladybug-tools.github.io/tree/master/eval )

It is intended to serve as boilerplate text for the new web site.

Let me know if you would like expansions on any particular topics.

There are also two additional pages

**Comment by mostaphaRoudsari** [comment]
@theo-armour 💯, Where is a good place to include the Bibliography? Do you want me to start a separate HTML page? or should we first collect them under an issue and move them to the page eventually?

**Comment by mostaphaRoudsari** [comment]
> Are we OpenFOAM+ or OpenFOAM?? And why?

OpenFOAM and OpenFOAM+ are very similar. We are currently using OpenFOAM from http://openfoam.com/ since they started the official support for Windows first.

**Comment by mostaphaRoudsari** [comment]
> A free and open source Grasshopper3D plugin for building energy and daylighting simulation with connections to ...

We should change the definitions for our plugins as they are no longer only for Grasshopper. Though this is an accurate definition for the legacy version. That will be a forthcoming challenge for us to clarify the [legacy version](https://github.com/mostaphaRoudsari/honeybee) from the [[+] version](https://github.com/ladybug-tools/honeybee). 

> make better early stage design decision based on timely, accurate and inexpensive calculations.

Ladybug tools is designed to support the whole design process including the **early stage**. It's True that most of our users using it for the early stage of design as most of Grasshopper and Dynamo users are the one who are involved mostly in the early stage of design but if one wants to use it later in the design it will be just as fine. For instance, we're support THERM, and OpenStudio HVAC systems which are mostly used in the detailed design phase.

- Questions directly related to EnergyPlus, Radiance or OpenStudio should be send to unmethours.com

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

Thank you for your suggestions. I agree with of them.

The easiest and much the fastest way, however, to reaching completion/closing on issues like these is to edit the text directly.

GitHub makes collaborating easy. Let's learn how to use these capabilities to the maximum.

Would you like to make the edits directly?
 
But more important: Did you like this effort? Will this kind of thing be helpful in the long term. Should I continue?

**Comment by mostaphaRoudsari** [comment]
@theo-armour Yes. Thanks. This is very helpful.

I wasn't sure if you want me to edit the file. Will be happy to edit the files directly and provide a reference here.
