### ISSUE TITLE
Finalize the List of Ladybug Tools Features

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug-tools.github.io#14]
Members of the Ladybug Community,

We are finalizing the list of features/capabilities of the different insects for this main website.  These features will appear at the bottom of the page for each insect like so:
http://www.ladybug.tools/eval/ladybug#facts and with full description here http://www.ladybug.tools/eval/ladybug#features

Here is the full list of features that we plan to post on the website:
https://docs.google.com/document/d/1v7L88tohVGoeNeRSywFstjQ_P2mpgRVN632nS7URHTc/edit?usp=sharing

If you feel that anything is missing, please let us know and we'll add it to the list

@sariths , if you could check over the list of Honeybee Radiance features, we would immensely appreciate it.

@TheodoreGalanos , if you could check the Butterfly features, that would be wonderful.

-Chris

**Comment by sariths** [comment]
@chriswmackey For Radiance-based features, following are worth mentioning: 

- LEEDv4 compliance studies including Annual Sunlight Exposure(ASE) and Spatial Daylight Autonomy(sDA). 
- Three Phase and Five Phase Annual Daylight Simulations (This is almost done).
- (Future) Photon Mapping Integration for Image-based and Annual Iluminance simulations.

**Comment by mostaphaRoudsari** [comment]
@sariths didn't we make the decision not to expose the three phase?

**Comment by sariths** [comment]
@mostaphaRoudsari Yes! And that is how it should be. I am just wondering if we should say that we are also running 3 phase under-the-hood. I am just not sure of how many people will get the distinction between 3 Phase and 5 Phase.

**Comment by mostaphaRoudsari** [comment]
@sariths as discussed let's use Multi-Phase daylight analysis then which covers both of them.

**Comment by TheodoreGalanos** [comment]
Hi Chris and everyone,

I am adding a few features of Butterfly below, including some future
additions given the young age of the bug.

1. Steady-state buoyant, turbulent flows using the boussinesq approximation
(heat transfer recipe)
2. Wind Driven Rain - FUTURE
3. Transient alternative of all current/future capability - FUTURE
4. Simulation of rotating machinery using Single and Multiple Reference
Frames (e.g. fan-assisted natural ventilation) - FUTURE
5. Indoor Environmental Quality studies (e.g. Air Change Effectiveness,
Mean Age of Air) - FUTURE
6. Indoor Thermal Comfort (e.g. PMV, Adaptive) - FUTURE

Might be forgetting smth as it is early, although I feel we have most of
the current stuff.

Kind regards,



Theodore Galanos
*Head of Building Physics & Computational Design*
*NEAPOLI | Environmental Engineering & Design*
p: +6 03 2166 6495 <+60%203-2166%206495>
f: +6 03 2181 6495 <+60%203-2181%206495>
w: www.neapoli.com.my
<https://www.facebook.com/GREEN.BUILDING.CONSULTANTS/>
<https://www.linkedin.com/company/neapoli-sdn-bhd>


*This email message (including attachments) contains information which may
be confidential and/or legally privileged. Unless you are the intended
recipient, you may not use, copy or disclose to anyone the message or
any information contained in the message or from any attachments that were
sent with this email, and If you have received this email message in error,
please advise the sender by email, and delete the message.
Unauthorised disclosure and/or use of information contained in this
email may be illegal.*

**Comment by mostaphaRoudsari** [comment]
@chriswmackey thanks for all the recent additions. They look great. Just a quick note about uppercase vs lowercase names. A number of images e.g. shadebenefit.PNG have uppercase letters which will cause issues unless you keep the names also uppercase in HTML file. As a rule let's keep all the extensions and names lowercase.

![image](https://user-images.githubusercontent.com/2915573/28686627-d38a6476-72d9-11e7-8033-d389f2c79139.png)
