### ISSUE TITLE
Auto generate the content of the new discourse website from the Grasshopper forum

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug-tools.github.io#19]
We need to move all the current discussions from [Grasshopper forum](http://www.grasshopper3d.com/group/ladybug) to the new [Discourse page](http://discourse.ladybug.tools/).

Discourse provides a REST API which should let us do it assuming we can get the initial data from the Grasshopper website.

1. Create the users
This should be done without sending the verification email right away. [Follow these instructions carefully](https://meta.discourse.org/t/creating-active-users-via-the-api-gem/33133/3).

2. Create the posts/topics and change the owner to the correct user.
Here is a good discussion on [how to seed a new forum](https://meta.discourse.org/t/seeding-a-new-forum-by-creating-users-and-content/49345/15).

3. Update email address and send a password reset to email address.
[Here is how this should be done!](https://meta.discourse.org/t/creating-active-users-via-the-api-gem/33133/19). Before sending these emails we need to send out an email and let everyone know about the changes.

**Comment by theo-armour** [comment]
btw, there's no sign up or register icon

**Comment by mostaphaRoudsari** [comment]
Thanks @theo-armour. Yes. It's deactivated intentionally. We don't want people to sign in right now before we transfer the discussions.

**Comment by devngc** [comment]
Hi @mostaphaRoudsari and @theo-armour,

Adding to this thread with a suggestion. There should be some guidelines about asking for help on the forum like the one David has [here](http://www.grasshopper3d.com/forum/topics/how-to-get-help-when-you-have-a-problem). 

Thanks,
Devang

**Comment by mostaphaRoudsari** [comment]
@devngc 💯! `discourse` has a specific page for this: http://forum.ladybug.tools/t/welcome-to-ladybug-tools-forum/8 Do you have a list in mind?

**Comment by devngc** [comment]
@mostaphaRoudsari,
Cool. I will put my thoughts on a google doc and will share with you.

**Comment by mostaphaRoudsari** [comment]
Done and done! I also closed all the discussion on the Grasshopper forum. This will ensure that everyone has to use the new forum to continue the conversation.
