### ISSUE TITLE
Post SF Meeting on 2017-08-09 Updates

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-tools.github.io#20]
@ladybug-tools/core 

I very much enjoyed the four of us sitting down together and thinking out loud. Thank you

My feeling is that open source in AEC is still at a really early stage. Thus Ladybug Tools is a leader in an emerging market. With care and consideration it could well continue to be a leader as the market blossoms. Fingers crossed we find cool ways of collaborating and helping the world build faster, smarter cheaper.

## Setting up private repo on Ladybug-tools 
We talked of doing this so we could keep management docs private. I said I would pay - thinking it would cost like $10 per month.. Turns out you pay by number of users. So $43.00 / month
for 7 users for us. I'm sure the money could be put to better use.

So - as Mostapha suggested - let's use Google Docs. 

Mostapha: how about you create a Google Drive folder and share it with us?

## Matt

Matt: I added you as an 'owner'  of this org - so you have same privileges as Mostapha, Chris and me. I added you to the team 'Core'. And I made Core a secret team. It's now only visible to us.

Matt: can you make you membership public? see https://github.com/orgs/ladybug-tools/people 

## Being good citizens

Never forget that GitHub is a social network for coders. In order to rise up in the hierarchy it's good to be popular.  So:

Follow all the peeps you can. Star their work. Watch their good works.

If you maintain a repo: 
* Make sure it has a great read me: see https://readmetips.github.io/
* Make sure you have added some good topics - five max
* Make sure it has a description understandable to newbs
* Include a link to where newbs can get a demo or see more

I'm sure we all have convoluted opinions about the value of social networks, but in helping Mostapha and Chis set up a business we should try to follow all possiblele leads - especially if they are free and take little time.

In particular I will stress the read me. Very few successful sites have read me files that suck

## Receipt of these messages

Chris and Matt: would you both acknowledge receipt of this message

## Business plan

As I mentioned, it's probably a good idea even for a bootstrap organization to have a business plan. I will be starting a search for a shortlist of good topics in the next few days and will share.

## ibpsa2017.github.io  

https://ibpsa2017.github.io/ is coming along. I see it as an archive for our workshop. I plan to add a few more posts and then will move back over to Ladybug Tools

Can I do things like add our PowerPoint etc?

## Room Builder Script - Python and JavaScript can be friends

Mostapha: Once I get back to working on Ladybug Web, we can start working on a 3D room with openings script . I hope we will be able to throw JSON files at each other really fast and well.

## Lots of Topics

If you have replies to multiple topics, it's best to start a new issue for each. So we can  eventually close the items individually.

**Comment by chriswmackey** [comment]
Just acknowledging that I've read this issue and I agree that a Google doc is much better than a private repo.

**Comment by mostaphaRoudsari** [comment]
Hi @theo-armour, Thank you for posting this. Finally released the honeybee[+] last night. That hopefully means that I can be more active here and on the forum for the next couple of weeks.

## Setting up private repo on Ladybug-tools
I agree that paying for a private repo in our case doesn't make sense. I can take care of the google drive and the google docs but there is no good way of have a conversation in a google doc. Should we also use slack to have the conversations on the topics? I should add that I don't check slack frequently but if everybody agrees to use it I can also start using it more frequently.

## Being a good citizen
I started with [Honeybee readme](https://github.com/ladybug-tools/honeybee/) and will continue writing the readme files for repos. I really appreciate your feedback before I want to write the readme for the rest of the repositories.

## Business plan
I will create the google doc and share it with everyone so @theo-armour can get this started.

## Room Builder
I'm super excited about making the room builder! I need a week or two to get back to a normal schedule and being able to contribute. I have been waiting to create this from [21 Apr 2014](https://github.com/mostaphaRoudsari/ladybug/issues/60)! Should we create a separate repository for the room?

**Comment by mdahlhausen** [comment]
Hi Theo and friends -

I've made my membership public.

Theo - do you need a copy of the powerpoint pdf, or do you have access to
it?

It's too bad we can't participate in the hackathon remotely.  I'd still be
up for a hackathon style event on our own sometime.

Business plan
Some more thoughts on income streams for you - ladybug merchandise
(t-shirts, stickers), donation targets to enable certain features, DOE
BTO/ARPA-E funding solicitations, foundation grants from climate-aligned
charities.
Room Builder
Not sure where this fits in, but the new OpenStudio 2D geometry tool is
out, with its own file structure.  Can we use the same file format?

I'll be adding a bunch of OpenStudio measure content in the coming weeks to
Unmet Hours Github / BCL, and have some default HVAC systems if you want to
add those to a model.  It's quite easy now with the OpenStudio command line
interface.  I'm not sure how this fits in with the workflow.
If you are just using ideal air loads for now, you may be interested in
this OpenStudio measure:
https://github.com/mdahlhausen/scrappEplus/tree/master/OpenStudio/Measures/ideal_loads_options

Regards,
-Matt

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

> Finally released the honeybee[+] last night. 

Yay!

### Google Doc
Started editing the Google Doc document. Thank you for creating. Even better will be to create a shared folder - so we can just add stuff we like

### Room Builder
I plane to build various ways of entering data including at least

- Really quick entering data by typing
- Entering data by dragging handles in 3D
- Entering data by voice recognition

What would your order of priority be for these methods?

@mdahlhausen 

### Powerpoint

I will add the one from your shared folder

### Room Builder
> Not sure where this fits in, but the new OpenStudio 2D geometry tool is out, with its own file structure.  Can we use the same file format?

Good idea and absolutely. [Bonus point for pointing me to link(s) with best specification/cheat sheet/whatever.

Room builder will think in code - everything parametric. Thus it can and should be made to output to any and all standard file formats. In fact the more ways it can output the data the better and more robust it becomes.

What do you think of podcasting a room as a form of data output? As with an actor with scary English voice intoning: "in a dark room, darkened because the Sun has a negative altitude of thirty four degrees, there is a narrow window with a width of just 36 centimeters just 98 centimeters from the north east coder of the room..." ;-) (late night writing)

Bye for now...

Theo

**Comment by theo-armour** [comment]
@mdahlhausen 

> the new OpenStudio 2D geometry tool

Is this http://www.gbxml.org/??

If so, then the action item would be opening, reading, displaying, (some) editing and saving gbxml data in 3D with your browser??

**Comment by mdahlhausen** [comment]
It is here: https://github.com/NREL/openstudio-geometry-editor

**Comment by theo-armour** [comment]
@mdahlhausen 

Thanks for the reply. I should have copied the whole quote:

> Not sure where this fits in, but the new OpenStudio 2D geometry tool is
> out, with its own file structure.  Can we use the same file format?

Do you you know what 3D file formats the OpenStudio Geometry Editor supports? And, if more than one, which one would you suggest I start with?

**Comment by mdahlhausen** [comment]
It has [its own schema](https://github.com/NREL/openstudio-geometry-editor/tree/develop/schema).  I'd suggest contact[Dan Macumber](https://github.com/macumber).  He can give you a fast briefing on their plans for the tool and what conversions they hope to support.

**Comment by theo-armour** [comment]
@mdahlhausen 

So I see exactly two examples of this format and there is little or no documentation on it, but it looks doable.

* https://github.com/NREL/openstudio-geometry-editor/blob/develop/test/e2e/fixtures/floorplan-2017-08-31.json
* https://github.com/NREL/openstudio-geometry-editor/blob/develop/measures/import_floorplan/tests/floorplan.json

Can you explain the rationale behind building on this format?

Would it not be more useful in the long run and in the big picture to read and write gbXML or IFC files?

**Comment by mostaphaRoudsari** [comment]
Hi @macumber, Can you help @theo-armour to get this information for OpenStuio new geometry editor? You may get yourself a 3d editor when you get @theo-armour involved! 😉

@theo-armour I was thinking that "say no to 2d" can be your motto! 😃

**Comment by macumber** [comment]
Hey @theo-armour it was great meeting you in SF!  I did not think that we could manage to create a full 3D web based browser in one year, that is why we shot for a 2D editor based on a new 2D format.  It is pretty easy to create more example files using one of the [releases](https://github.com/NREL/openstudio-geometry-editor/releases), just download the standalone editor and run it in a Chrome browser.  Basic instructions on how to use it are [here](http://nrel.github.io/OpenStudio-user-documentation/reference/geometry_editor/).

There is a [JSON schema](https://github.com/NREL/openstudio-geometry-editor/blob/develop/schema/geometry_schema.json) for the file format but you are right it could use more documentation.

As an interesting note, we don't actually convert this 2D format to OSM directly.  We first convert it to ThreeJS so we are able to preview it in the VA3C viewer you helped me write! (We actually use a slight variation of the ThreeJS format I can explain if you are interested).  Anyway, if you make an editor writing gbXML, ThreeJS, or this new 2D format we can convert it to OSM.  Can't really do much with IFC, I'd recommend staying away from that unless you really want to go down that path, it is not a lightweight format.

Let me know if you have any questions, feel free to email or tag me on GitHub (I probably respond to email better since I sometimes miss GitHub notifications).

**Comment by macumber** [comment]
Also note that the geometry editor is itself open source so feel free to extend it or use bit and pieces.  It has pretty lightweight dependencies.  We'll be adding more features in the near future including pitched roofs, components (windows, doors, etc), and split levels.

**Comment by theo-armour** [comment]
@chriswmackey 
>  I was thinking that "say no to 2d" can be your motto!
Bingo!

@macumber 

It was good to meet up at last at IBPSA. And thank you for the informative presentations. 

I have had a quick look at the Geometry Editor. Looks like quite an effort. I will continue having the exploration,
You can see we did in our presentation here: https://ibpsa2017.github.io/

Back to the question at hand:

Mostapha and I have been talking about jointly developing Python/JavaScript projects

Caclulate in Python/Visualize in JavaScript ( 3D in your browser) being the overarching thought. This effort should be generic. It should be able to handle a variety of circumstances.

Therefore we need some data format that we can use to throw building at each other. It would be nice if this is an industry standard. Ultimately I would like to support many formats including IFC (we agree on its weight). But where to start?

The main thing I am looking for is a good number of models to play with, test and debug. My searches have turned up very few sources with engineering quality AEC models. (Yes, the 3D Warehouse has a ton of models - but these are only of rendering quality).

Here is what I have so far as viable 3D file formats and sources:

* osm:  https://github.com/NREL/openstudio-standards/tree/master/openstudio-standards/data/geometry
* gbXML: https://github.com/GreenBuildingXML/Sample-gbXML-Files
* cityGML: https://www.citygml.org/samplefiles/
  
The main problem is there's not a large number of sample files to play with - thought I expext there's a good amount of data for cityGML from some of the European cities.

BTW, I am finding that going from XML to JSON is a twenty lines of code. Probably same going the other way. So XML = JSON. So we may end up using JSON for quick and dirty intermediate data transfers and then save to XML.

Anyway I would be very pleased to hear:

* Your thoughts as to what file format the Ladybug Tools team should prioritize for collaboration - along with a bit of the why. 
* Your suggestions for any places or ways of sourcing more sample files

**Comment by macumber** [comment]
My suggestion would be use gbXML for individual buildings and CityGML for city level.  I have found gbXML to be the best format for interoperability in building energy modeling.  I am very positive about the future of CityGML, it looks like the right balance between simplicity and features.  However, I have not found a lot of data sources for CityGML in the US at this time.  We've been using GeoJSON for our urban modeling which is very simple (but it is a 2D format).

OSM is not meant to be written to outside of the OpenStudio API, I would not recommend writing it directly.  However, OpenStudio is pretty good at translation so I would suggest using the OpenStudio command line interface to convert different formats to gbXML.

You can use OpenStudio to create gbXML example files.  You could try using the new OpenStudio Application in our [latest release](https://github.com/NREL/OpenStudio/releases/tag/v2.2.1) that includes the geometry editor to create buildings from floorplans and then exporting gbXML files.

**Comment by theo-armour** [comment]
@macumber @co

Thanks for you good advice - which I am acting on.

Here's a very preliminary version:

http://www.ladybug.tools/spider/#sandbox/read-gbxml/read-gbxml-3d-polyloop.html

This version has issues with PolyLoops that are note extremely orthogonal. And has no light/shading yet.
 
A separate version displaying RectangularGeomtery is also in the works

BTW, I'm using this page to build test cases: https://greenspacelive.com/site/building-generator/

**Comment by macumber** [comment]
That is awesome @theo-armour :-)  I know that Stephen Roth, the maintainer of [gbxml.org](https://gbxml.org), would be interested in seeing this when you are ready.  He has been wanting to add a gbMXL preview capability to his site for a while.  There is contact info on his site if you want to give him a preview of what you are working on.
