### ISSUE TITLE
FAQ Updates

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-tools.github.io#22]
from:
https://github.com/ladybug-tools/ladybug-tools.github.io/commit/ddba66195e4d063720d6f2339224a5e92a259d1f

> Finished adding faq
> There is a missing link for question 13 that can be added once we have
> it somewhere on the page.
> 
> @theo-armour we added the FAQ with answers to the about page and removed
> the .md file. Let us know your thoughts on the questions and answers as
> well as links. Will be happy to provide more links if there is any
> missing from the page.
> www.ladybug.tools/eval/about#faq

I'm moving the discussion to issues, because it'a a very interesting one.

Generally, the FAQ is looking good. And there's a lot of text with good background information.

Some observations:

Questions 7 and 8 are identical and yet have different answers.

If I were to add another question, I'm not sure where I would know where to put it. It would be nice to have some categories or tags for the questions. This might help identify missing questions.

This makes me think I should create an faqTips page the way I did for readmeTips.github.io and have it list all the typical categories.

Also we should think about nice and logical ways of splitting up the read me, support, about and general text content through the site.

And, me being me. I would like to see all text like this in easy to update Markdown format. ;-)

**Comment by mostaphaRoudsari** [comment]
> Questions 7 and 8 are identical and yet have different answers.
This is a mistake! I will fix it.

**Comment by chriswmackey** [comment]
Yea, question 7 should be "Is Ladybug Tools validated?"

Thanks for catching that @theo-armour

**Comment by mostaphaRoudsari** [comment]
@theo-armour, question 7 is fixed! Thanks for catching that.

I like the idea of tagging the questions but I'm not sure where to start.

> Also we should think about nice and logical ways of splitting up the read me, support, about and general text content through the site.

I'm not sure if I understand what are you proposing here. You want use to put them under different pages? We don't have text for support, do we?

**Comment by mostaphaRoudsari** [comment]
This is fixed!
