### ISSUE TITLE
update the links on the network chart

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug-tools.github.io#24]
review the links. I bet most of them are not working.

**Comment by chriswmackey** [comment]
@mostapharoudsari ,

I took care of this over the past week. All of the links should be working. I also tried to compose the static state of the diagram so that it's compact within the web browser (when you first open the page).

**Comment by mostaphaRoudsari** [comment]
Perfect! Thanks.
