### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by devngc** [ladybug-tools/ladybug-tools.github.io#26]
Hi All,
Following are some of my observations on Ladybug tools website recently opened to public. The first two screenshots are as viewed from iphone6.

Some overlap
![dynawards](https://user-images.githubusercontent.com/20086924/31059161-53319718-a71d-11e7-9d33-b0cea7d4eff6.JPG)

Some spacing may be
![membership_contact](https://user-images.githubusercontent.com/20086924/31059162-56516270-a71d-11e7-877b-e314bdafddf7.JPG)

Empty node
![emptynode](https://user-images.githubusercontent.com/20086924/31059166-664e697a-a71d-11e7-8e2f-05bd25749f96.JPG)

And some more
![patreon](https://user-images.githubusercontent.com/20086924/31059167-67f066a2-a71d-11e7-88be-253cc3a2cc16.JPG)

I also think, there should be a link to FAQ in the footer.

Thank you!

**Comment by mostaphaRoudsari** [comment]
Hi @devngc, thanks.

I checked the issues related to Patreon page and addressed number 3. Number 1 and 2 are already as you mentioned. Can you check again?

**Comment by devngc** [comment]
@mostaphaRoudsari,
Looks good! Thank you quickly addressing this!

**Comment by chriswmackey** [comment]
@devngc ,
Thanks for checking this.It looks like all of the issues that you posted are related to viewing the site on a phone. The Dynaward one can be fixed (I'll do this soon)

The overlap of membership is pretty bad on some cases.


I think the only way to address this is to shorten the name "Membership" on the bottom to something like "Members". What do you think @mostapharoudsari ?  I feel like we could still use the word "membership" everywhere else.

The empty node in the web is deliberate. It's needed to get the web going the structure we want.

**Comment by mostaphaRoudsari** [comment]
@devngc, I followed @chriswmackey's suggestion for the about page. It looks fine on the chrome's development tools for iphone 6. Let me know your thoughts and I can update all the footers for other pages: http://www.ladybug.tools/membership.html#patronwall

**Comment by devngc** [comment]
@mostaphaRoudsari,
Thank you for this edit. I also used the developer tools of Chrome when I last commented. Now I checked in a real device. Looks good! Thanks again
