### ISSUE TITLE
SSL Certificate for the website

### ISSUE THREAD

**Issue by devngc** [ladybug-tools/ladybug-tools.github.io#28]
Please check [this](https://medium.freecodecamp.org/free-https-c051ca570324) article. Please ignore if @theo-armour already has plans in place to address this.

**Comment by theo-armour** [comment]
@devngc 

Thanks for the heads up.

I agree that adding https to http://www.ladybug.tools would be a really good thing. And its not just http://www.ladybug.tools/spider/ that would benefit but also http://www.ladybug.tools/honeybee.html and all the other Ladybug Tools.

The domain name registrar for ladybug.tools is Google Domains but the actual admin name is private. I do believe, however, that the domain owner is @mostaphaRoudsari. If the change to HTTPS is to be made, I think Mostapha has to get the ball rolling.

BTW, I am currently running into a number of places where HTPS is required so I use rawgit.com to get around the limitations.

Examples:
* https://rawgit.com/ladybug-tools/ladybug-web/gh-pages/solar-calculator-ladybug-web/solar-calculator-ladybug-web-r1.js
* https://cdn.rawgit.com/mrdoob/three.js/r89/build/three.min.js

**Comment by mostaphaRoudsari** [comment]
It's hosted on GitHub Pages! As of yesterday we can get this fixed easily with no extra work: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

I just need to follow the directions on the page. Then we need to add ssl to our form which is a different story but is now possible.

**Comment by mostaphaRoudsari** [comment]
Done and done!

![screenshot 22](https://user-images.githubusercontent.com/2915573/39673584-18b50562-510d-11e8-81b6-0ae426863f4d.png)


![screenshot 21](https://user-images.githubusercontent.com/2915573/39673573-e94b3616-510c-11e8-8ff5-18ce8767a9bb.png)
