### ISSUE TITLE
Add a page for publications

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug-tools.github.io#7]
See this (https://github.com/ladybug-tools/ladybug-tools.github.io/issues/2#issuecomment-305300402)

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

Often this type of data is treated as a bibliography of tables of references.

One should be able to click the reference to open it and also be able to copy the reference into another work.

**Comment by mostaphaRoudsari** [comment]
@theo-armour, thanks. [Daysim publications page](http://daysim.ning.com/page/publications) could be a good example. They don't have active links to publications though which is not good.

**Comment by theo-armour** [comment]
See

https://github.com/ladybug-tools/ladybug-tools.github.io/blob/master/eval/bibliography.md
