### ISSUE TITLE
Added 'New Ladybug Tools Web Site' as a GitHub Project

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-tools.github.io#9]
See:

## https://github.com/ladybug-tools/ladybug-tools.github.io/projects/1

This may or may not be helpful. And the cards I have added may or may not be good.

But we should decide if Projects could be useful to us. And, if so, how?

We might also consider use of GitHub Milestones

**Comment by mostaphaRoudsari** [comment]
Hi @theo-armour, I found something like projects mostly useful closer to a public release when we want to track critical items. It's nice to have it on GitHub but so far I have been using [Trello](https://trello.com/).

I personally think issues are flexible enough to assign all we need using labels, assignee and milestone. Having one more place to check (projects) doesn't sound pleasing to me unless it brings something quite helpful to the table.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

All sounds good. Once I move the links I found to somewhere safe, I will delete the project.
